const request = require('request');


const fetchBreedDescription = function(breedName, callback) {
  const url = `https://api.thecatapi.com/v1/breeds/search?q=${breedName}`
  request(url, (error, response, body) => {
    
    console.log("statusCode: ", response && response.statusCode);
    const data = JSON.parse(body);
    const breedInfo = data[0];

    if (error !== null) {
      // return autogenerated error message
      callback(error, null);
      // end script
      process.exit();

    } else {
      if (data.length === 0) {
        // return custom error message
        error = "No breed with that name found. Please check the spelling and try again.";
        callback(error, null);
        process.exit();

      } else {
        // return request
        callback(null, breedInfo.description);
      }
    }
  });

};

//fetchBreedDescription('norwegian')

module.exports = { fetchBreedDescription };